// <auto-generated />
using System;
using JuanBosch.App.Models.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuanBosch.App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250924022900_MakeHospitalMedicDateNullable")]
    partial class MakeHospitalMedicDateNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JuanBosch.App.Models.Address.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.DoctorAddress", b =>
                {
                    b.Property<int>("DoctorAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorAddressId"));

                    b.Property<string>("DoctorHouseNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DoctorStreet")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("DoctorAddressId");

                    b.HasIndex("SectorId");

                    b.ToTable("DoctorAddresses", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId1")
                        .HasColumnType("int");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("ProvinceId1");

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectorId"));

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipalityId1")
                        .HasColumnType("int");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SectorId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("MunicipalityId1");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsEnsurance", b =>
                {
                    b.Property<int>("ArsEnsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArsEnsuranceId"));

                    b.Property<string>("EnsuranceDirection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EnsuranceEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnsuranceFax")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EnsuranceName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("EnsurancePhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("EnsurancePhone2")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<TimeOnly>("EnsuranceSchedule")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("EnsuranceUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ArsEnsuranceId");

                    b.ToTable("ArsEnsurance", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsPlans", b =>
                {
                    b.Property<int>("ArsPlansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArsPlansId"));

                    b.Property<string>("AfiliationNumberArs")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ArsEnsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("ArsPlansName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CoveragePlanArs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("InternationalCoverage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPlanActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaxLimitArs")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("ArsPlansId");

                    b.HasIndex("ArsEnsuranceId");

                    b.ToTable("ArsPlans", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Bloods.Blood", b =>
                {
                    b.Property<int>("BloodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BloodId"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("ConsentBlood")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BloodId");

                    b.ToTable("Blood", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Dates.DateDoctor", b =>
                {
                    b.Property<int>("DateDoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DateDoctorId"));

                    b.Property<string>("DateDoctorIndicatedAnalisis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("DateDoctorNextDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DateDoctorNotes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DateDoctorSintoms")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("DateDoctorTreatment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("MedicEvaluationId")
                        .HasColumnType("int");

                    b.HasKey("DateDoctorId");

                    b.HasIndex("MedicEvaluationId")
                        .IsUnique();

                    b.ToTable("DateDoctors", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Dates.DateMedic", b =>
                {
                    b.Property<int>("DateMedicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DateMedicId"));

                    b.Property<int>("ConsultationType")
                        .HasColumnType("int")
                        .HasColumnName("ConsultationTypeId");

                    b.Property<int>("DateDoctorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateMedicDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("HospitalMedicDate")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("DateMedicId");

                    b.HasIndex("DateDoctorId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("DateMedics", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Doctors.DoctorEnsurance", b =>
                {
                    b.Property<int>("DoctorEnsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorEnsuranceId"));

                    b.Property<int>("ArsEnsuranceId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("MedicCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("DoctorEnsuranceId");

                    b.HasIndex("ArsEnsuranceId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorEnsurances", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Doctors.DoctorMedic", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<int>("DoctorAddressId")
                        .HasColumnType("int");

                    b.Property<string>("DoctorEmail")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("varchar(55)");

                    b.Property<string>("DoctorExecatur")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("DoctorIdCard")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("DoctorPassport")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("DoctorPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("DoctorSpeciality")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.HasKey("DoctorId");

                    b.HasIndex("DoctorAddressId");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.MedicEvaluations.MedicEvaluation", b =>
                {
                    b.Property<int>("MedicEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicEvaluationId"));

                    b.Property<int>("BreathingEva")
                        .HasColumnType("int");

                    b.Property<int>("DateDoctorId")
                        .HasColumnType("int");

                    b.Property<string>("HeartRateEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<string>("HeightEva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OtherInfoEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<int>("PresurreEva")
                        .HasColumnType("int");

                    b.Property<string>("PreviousSickNessEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<int>("WeightEva")
                        .HasColumnType("int");

                    b.HasKey("MedicEvaluationId");

                    b.ToTable("MedicEvaluations", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.MedicRecords.MedicRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("FollowUpMedicRecord")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("SignsMedicRecord")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("RecordId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("MedicRecords", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HouseStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("SectorId");

                    b.ToTable("PatientDirections", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Patients.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("ArsPlansId")
                        .HasColumnType("int");

                    b.Property<int>("BloodId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PatientBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("PatientEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientEmergencieContact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientFisRecord")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientGender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PatientIdCard")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientPassport")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PatientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PatientId");

                    b.HasIndex("AddressId");

                    b.HasIndex("ArsPlansId");

                    b.HasIndex("BloodId");

                    b.HasIndex("PatientEmail");

                    b.HasIndex("PatientIdCard");

                    b.HasIndex("PatientPassport");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientsDoctors.PatientsDoctor", b =>
                {
                    b.Property<int>("PatientDoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientDoctorId"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("PatientDoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "PatientId")
                        .IsUnique()
                        .HasDatabaseName("IX_PatientDoctor_DoctorId_PatientId");

                    b.ToTable("PatientDoctors", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.DoctorAddress", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Sector", "Sector")
                        .WithMany("DoctorAddresses")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Province", null)
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId1");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Municipality", null)
                        .WithMany("Sectors")
                        .HasForeignKey("MunicipalityId1");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsPlans", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Ars.ArsEnsurance", "ArsEnsurance")
                        .WithMany("Plans")
                        .HasForeignKey("ArsEnsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArsEnsurance");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Dates.DateDoctor", b =>
                {
                    b.HasOne("JuanBosch.App.Models.MedicEvaluations.MedicEvaluation", "MedicEvaluation")
                        .WithOne("DateDoctor")
                        .HasForeignKey("JuanBosch.App.Models.Dates.DateDoctor", "MedicEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicEvaluation");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Dates.DateMedic", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Dates.DateDoctor", "DateDoctor")
                        .WithMany("DateMedics")
                        .HasForeignKey("DateDoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Doctors.DoctorMedic", "Doctor")
                        .WithMany("DateMedics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Patients.Patient", "Patient")
                        .WithMany("DateMedics")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateDoctor");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Doctors.DoctorEnsurance", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Ars.ArsEnsurance", "ArsEnsurance")
                        .WithMany("DoctorEnsurances")
                        .HasForeignKey("ArsEnsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Doctors.DoctorMedic", "DoctorMedic")
                        .WithMany("DoctorEnsurances")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArsEnsurance");

                    b.Navigation("DoctorMedic");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Doctors.DoctorMedic", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.DoctorAddress", "DoctorAddress")
                        .WithMany("Doctors")
                        .HasForeignKey("DoctorAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorAddress");
                });

            modelBuilder.Entity("JuanBosch.App.Models.MedicRecords.MedicRecord", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Doctors.DoctorMedic", "DoctorsMedics")
                        .WithMany("MedicRecords")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Patients.Patient", "Patient")
                        .WithOne("MedicRecord")
                        .HasForeignKey("JuanBosch.App.Models.MedicRecords.MedicRecord", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoctorsMedics");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Sector", "Sector")
                        .WithMany("PatientDirections")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Patients.Patient", b =>
                {
                    b.HasOne("JuanBosch.App.Models.PatientDirection", "PatientDirection")
                        .WithMany("Patient")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("JuanBosch.App.Models.Ars.ArsPlans", "ArsPlans")
                        .WithMany("Patients")
                        .HasForeignKey("ArsPlansId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Bloods.Blood", "Blood")
                        .WithMany("Patients")
                        .HasForeignKey("BloodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArsPlans");

                    b.Navigation("Blood");

                    b.Navigation("PatientDirection");
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientsDoctors.PatientsDoctor", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Doctors.DoctorMedic", "DoctorMedic")
                        .WithMany("PatientDoctor")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Patients.Patient", "Patient")
                        .WithMany("PatientDoctor")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoctorMedic");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.DoctorAddress", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.Navigation("DoctorAddresses");

                    b.Navigation("PatientDirections");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsEnsurance", b =>
                {
                    b.Navigation("DoctorEnsurances");

                    b.Navigation("Plans");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsPlans", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Bloods.Blood", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Dates.DateDoctor", b =>
                {
                    b.Navigation("DateMedics");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Doctors.DoctorMedic", b =>
                {
                    b.Navigation("DateMedics");

                    b.Navigation("DoctorEnsurances");

                    b.Navigation("MedicRecords");

                    b.Navigation("PatientDoctor");
                });

            modelBuilder.Entity("JuanBosch.App.Models.MedicEvaluations.MedicEvaluation", b =>
                {
                    b.Navigation("DateDoctor")
                        .IsRequired();
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.Navigation("Patient");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Patients.Patient", b =>
                {
                    b.Navigation("DateMedics");

                    b.Navigation("MedicRecord")
                        .IsRequired();

                    b.Navigation("PatientDoctor");
                });
#pragma warning restore 612, 618
        }
    }
}
