// <auto-generated />
using System;
using JuanBosch.App.Models.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuanBosch.App.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250715002537_ArsEnsuranceAdded")]
    partial class ArsEnsuranceAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JuanBosch.App.Models.Address.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryLanguage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<string>("MunicipalityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int?>("ProvinceId1")
                        .HasColumnType("int");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("ProvinceId1");

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ProvinceId");

                    b.HasIndex("CountryId");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SectorId"));

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int?>("MunicipalityId1")
                        .HasColumnType("int");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SectorId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("MunicipalityId1");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsEnsurance", b =>
                {
                    b.Property<int>("ArsEnsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArsEnsuranceId"));

                    b.Property<string>("EnsuranceDirection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EnsuranceEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnsuranceFax")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("EnsuranceName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("EnsurancePhone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("EnsurancePhone2")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<TimeOnly>("EnsuranceSchedule")
                        .HasColumnType("time(6)");

                    b.Property<DateTime>("EnsuranceUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ArsEnsuranceId");

                    b.ToTable("ArsEnsurance", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsPlans", b =>
                {
                    b.Property<int>("ArsPlansId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArsPlansId"));

                    b.Property<string>("AfiliationNumberArs")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<int>("ArsEnsuranceId")
                        .HasColumnType("int");

                    b.Property<string>("ArsPlansName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CoveragePlanArs")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("InternationalCoverage")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPlanActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaxLimitArs")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("ArsPlansId");

                    b.HasIndex("ArsEnsuranceId");

                    b.ToTable("ArsPlans", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Blood.Blood", b =>
                {
                    b.Property<int>("BloodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BloodId"));

                    b.Property<string>("BloodType")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<bool>("ConsentBlood")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("BloodId");

                    b.ToTable("Blood", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.MedicEvaluation.MedicEvaluation", b =>
                {
                    b.Property<int>("MedicEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MedicEvaluationId"));

                    b.Property<int>("BreathingEva")
                        .HasColumnType("int");

                    b.Property<string>("HeartRateEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<string>("HeightEva")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OtherInfoEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<int>("PresurreEva")
                        .HasColumnType("int");

                    b.Property<string>("PreviousSickNessEva")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("varchar(900)");

                    b.Property<int>("WeightEva")
                        .HasColumnType("int");

                    b.HasKey("MedicEvaluationId");

                    b.ToTable("MedicEvaluations", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("PatientBirthDate")
                        .HasColumnType("date");

                    b.Property<string>("PatientEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientGender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PatientIdCard")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PatientPassport")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PatientPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PatientId");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("PatientEmail");

                    b.HasIndex("PatientIdCard");

                    b.HasIndex("PatientPassport");

                    b.ToTable("Patients", null, t =>
                        {
                            t.HasCheckConstraint("CK_Patient_Identification", "PatientIdCard IS NOT NULL OR PatientPassport IS NOT NULL");
                        });
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HouseStreet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.HasKey("AddressId");

                    b.HasIndex("CountryId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("SectorId");

                    b.ToTable("PatientDirections", (string)null);
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Province", null)
                        .WithMany("Municipalities")
                        .HasForeignKey("ProvinceId1");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Municipality", null)
                        .WithMany("Sectors")
                        .HasForeignKey("MunicipalityId1");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsPlans", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Ars.ArsEnsurance", "ArsEnsurance")
                        .WithMany("Plans")
                        .HasForeignKey("ArsEnsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArsEnsurance");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Patient", b =>
                {
                    b.HasOne("JuanBosch.App.Models.PatientDirection", "PatientDirection")
                        .WithOne("Patient")
                        .HasForeignKey("JuanBosch.App.Models.Patient", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("PatientDirection");
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.HasOne("JuanBosch.App.Models.Address.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuanBosch.App.Models.Address.Sector", "Sector")
                        .WithMany("PatientDirections")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Municipality");

                    b.Navigation("Province");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Municipality", b =>
                {
                    b.Navigation("Sectors");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Province", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Address.Sector", b =>
                {
                    b.Navigation("PatientDirections");
                });

            modelBuilder.Entity("JuanBosch.App.Models.Ars.ArsEnsurance", b =>
                {
                    b.Navigation("Plans");
                });

            modelBuilder.Entity("JuanBosch.App.Models.PatientDirection", b =>
                {
                    b.Navigation("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
